pools:
  standard: 'singlecellmm10standard'
  highmem: 'singlecellmm10highmem'
  multicore: 'singlecellmm10multicore'


# Reference genome to align to in fasta format. Should be indexed by aligner and samtools
ref_genome: /refdata/mm10_build38_mouse.fasta

# Chromosomes for copy number analysis
chromosomes: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', 'X', 'Y']

mutationseq: /usr/local/museq/
mutationseq_model: /usr/local/museq/models_anaconda/model_v4.1.2_anaconda_sk_0.13.1.npz

gc_windows: null

one_split_job: True

memory:
  low: 2
  med: 6
  high: 15

max_cores: null

adapter: 'CTGTCTCTTATACACATCTCCGAGCCCACGAGAC'

adapter2: 'CTGTCTCTTATACACATCTGACGCTGCCGACGA'