# Only build tags
if: tag IS present
language: python
python:
- 3.7
env:
  matrix:
  - PACKAGENAME=single_cell_pipeline
before_install:
- echo $TEST
- wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- "./miniconda.sh -b"
- export PATH=$HOME/miniconda3/bin:$PATH
- conda update --yes -q conda
- conda config --set always_yes true
- conda config --set anaconda_upload no
install:
- conda install -q python=$TRAVIS_PYTHON_VERSION conda-build anaconda-client setuptools
  nose numpy cython
- conda build conda/$PACKAGENAME -c shahcompbio -c r -c conda-forge -c bioconda
- conda install --use-local $PACKAGENAME
script:
- python -c "import single_cell"
after_success:
- chmod +x ./deploy_anaconda.sh
deploy:
- provider: script
  script: "./deploy_anaconda.sh"
  on:
    tags: true
  skip_cleanup: true
