# ------------------------------ Modify for each run ------------------------------ #
queue: shahlab.q
hosts: 'h=node0501.genesis.hpc.bcgsc.ca|node0502.genesis.hpc.bcgsc.ca|node0503.genesis.hpc.bcgsc.ca|node0504.genesis.hpc.bcgsc.ca|node0505.genesis.hpc.bcgsc.ca|node0506.genesis.hpc.bcgsc.ca|node0507.genesis.hpc.bcgsc.ca|node0508.genesis.hpc.bcgsc.ca|node0509.genesis.hpc.bcgsc.ca|node0510.genesis.hpc.bcgsc.ca|node0511.genesis.hpc.bcgsc.ca|node0512.genesis.hpc.bcgsc.ca|node0513.genesis.hpc.bcgsc.ca|node0514.genesis.hpc.bcgsc.ca'


python: /shahlab/pipelines/virtual_environments/single_cell_analysis_pipeline/bin/python
bcl2fastq: /gsc/software/linux-x86_64-centos6/bcl2fastq-2.17/bin/bcl2fastq
java: /shahlab/pipelines/apps_centos6/jdk1.8.0_51/bin/java
readcounter: /shahlab/pipelines/apps_centos6/readcounter/readCounter
samtools: /shahlab/pipelines/apps_centos6/samtools-1.2/samtools  
fastqc: /shahlab/pipelines/apps_centos6/FastQC/fastqc
bwa: /shahlab/pipelines/apps_centos6/bwa-0.7.12/bwa
R: /gsc/software/linux-x86_64-centos6/R-3.1.1/bin/R
Rscript: /gsc/software/linux-x86_64-centos6/R-3.1.1/bin/Rscript
# Path to NextSeq directory
nextseq_dir: /shahlab/dgrewal/upd_asteif/wdir/170322_NS500668_0178_AHJYLHAFXX/
R_libs: /shahlab/pipelines/apps_centos6/R_libs_titan_1.5.5/
# Path where files will be output
out_dir: /shahlab/dgrewal/upd_asteif/wdir/output1

# ------------------------------- No need to modify ------------------------------- #

# Read group information (PU and LB are read from the NextSeq SampleSheet.csv file)
read_group:  
  # Platform
  PL: illumina
  
  # Sequencing centre identifier (either BCCAGSC or UBCBRC)
  CN: UBCBRC

# Reference genome to align to in fasta format. Should be indexed by aligner and samtools
ref_genome: /shahlab/pipelines/reference/GRCh37-lite.fa

# Minimum base quality to count a read
min_bqual: 20

# Minimum mapping quality to count a read
min_mqual: 20

# Picard jar file (version 1.141 or higher)
picard_jar: /shahlab/pipelines/apps_centos6/picard-tools-1.141/picard.jar


# Identifier for analysis
analysis_id: test

# Optional library info file (will add cell call to HMMcopy plots)
library_info: /shahlab/dgrewal/upd_asteif/wdir/170322_NS500668_0178_AHJYLHAFXX/SampleSheet.csv

# Bin size
bin_size: 500000

# Optional mappability cutoff
map_cutoff: 0.9

# Number of states
num_states: 7

# HMMcopy parameters
parameters:
    mu: 0,0.5,1.0,1.5,2.0,2.5,3.0

    m: 0,0.5,1.0,1.5,2.0,2.5,3.0

    kappa: 25,100,700,100,25,25,25

    e: 0.995

    s: 35

# Binned GC content file
gc_wig_file: /genesis/extscratch/shahlab/pipelines/reference/GRCh37-lite.gc.ws_500000.wig

# Binned mappability file
map_wig_file: /genesis/extscratch/shahlab/pipelines/reference/GRCh37-lite.map.ws_125_to_500000.wig
