package:
  name: single_cell_pipeline
  version: '0.0.1'

source:
  git_url: https://svn.bcgsc.ca/bitbucket/scm/sc/single_cell_pipeline.git
  git_rev: v0.0.1

requirements:
  build:
    - python

  run:
    - python
    - hmmcopy_utils
    - samtools
    - bwa
    - fastqc
    - picard
    - cutadapt
    - trim-galore
    - pypeliner
    - bioconductor-hmmcopy
    - r-plyr
    - r-getopt
    - matplotlib
    - seaborn
    - statsmodels
    - pyyaml
    - pyvcf
    - samtools
    - vcftools
    - tabix
    - bcftools
    - scikit-learn
    - intervaltree
    - pysam
    - matplotlib
    - seaborn
    - gatk
    - strelka

about:
  home: http://shahlab.ca
  summary: 'Bioinformatics pipeline for single cell analysis'

