pools:
  standard: 'singlecellgrch37standard'

  highmem: 'singlecellgrch37highmem'

  multicore: 'singlecellgrch37multicore'

picard_wgs_params:
  # Minimum base quality to count a read
  min_bqual: 20

  # Minimum mapping quality to count a read
  min_mqual: 20

  # Count unpaired reads for wgs metrics
  count_unpaired: false

# HMMcopy parameters
hmmcopy_params:
  diploid:
    mu: 0,0.5,1.0,1.5,2.0,2.5,3.0

    m: 0,0.5,1.0,1.5,2.0,2.5,3.0

    kappa: 25,100,700,100,25,25,25

    e: null

    g: null

    s: null

    nu: null

    eta: null

    lambda: null

    # Optional mappability cutoff
    map_cutoff: 0.9

    # Number of states
    num_states: 7

    # Minimum mapping quality to count a read
    min_mqual: 20

    # Bin size
    bin_size: 150000

    # Binned GC content file
    gc_wig_file: /refdata/GRCh37-lite.gc.ws_150000.wig

    # Binned mappability file
    map_wig_file: /refdata/GRCh37-lite.map.ws_125_to_150000.wig

    exclude_list: /refdata/repeats.satellite.regions

    smoothing_function: loess

    auto_ploidy: null

  tetraploid:
    mu: 0,0.25,0.5,0.75,1.0,1.25,1.5

    m: 0,0.25,0.5,0.75,1.0,1.25,1.5

    kappa: 25,100,700,100,25,25,25

    e: null

    g: null

    s: null

    nu: null

    eta: null

    lambda: null

    # Optional mappability cutoff
    map_cutoff: 0.9

    # Number of states
    num_states: 7

    # Minimum mapping quality to count a read
    min_mqual: 20

    # Bin size
    bin_size: 150000

    # Binned GC content file
    gc_wig_file: /refdata/GRCh37-lite.gc.ws_150000.wig

    # Binned mappability file
    map_wig_file: /refdata/GRCh37-lite.map.ws_125_to_150000.wig

    exclude_list: /refdata/repeats.satellite.regions

    smoothing_function: loess

    auto_ploidy: null

  triploid:
    mu: 0,0.33,0.66,1.0,1.33,1.66,2.0

    m: 0,0.33,0.66,1.0,1.33,1.66,2.0

    kappa: 25,100,700,100,25,25,25

    e: null

    g: null

    s: null

    nu: null

    eta: null

    lambda: null

    # Optional mappability cutoff
    map_cutoff: 0.9

    # Number of states
    num_states: 7

    # Minimum mapping quality to count a read
    min_mqual: 20

    # Bin size
    bin_size: 150000

    # Binned GC content file
    gc_wig_file: /refdata/GRCh37-lite.gc.ws_150000.wig

    # Binned mappability file
    map_wig_file: /refdata/GRCh37-lite.map.ws_125_to_150000.wig

    exclude_list: /refdata/repeats.satellite.regions

    smoothing_function: loess

    auto_ploidy: null

# Reference genome to align to in fasta format. Should be indexed by aligner and samtools
ref_genome: /refdata/GRCh37-lite.fa

# Chromosomes for copy number analysis
chromosomes: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', 'X', 'Y']

mutationseq: /usr/local/museq/

mutationseq_model: /usr/local/museq/models_anaconda/model_v4.1.2_anaconda_sk_0.13.1.npz

plot_mad_threshold: 0.2

plot_numreads_threshold: 100000

gc_windows: '/refdata/gc_windows.txt'

one_split_job: True

memory:
  low: 2

  med: 6

  high: 15

max_cores: null

aligner: bwa-mem

adapter: 'CTGTCTCTTATACACATCTCCGAGCCCACGAGAC'

adapter2: 'CTGTCTCTTATACACATCTGACGCTGCCGACGA'
